exports.USER_TYPE = ["ATHLETE", "PERFORMANCE_EXPERT"];
exports.USER_ATHLETE = "ATHLETE";
exports.USER_PERFORMANCE_EXPERT = "PERFORMANCE_EXPERT";

exports.ATHLETE_STATUS = ["ONBOARDING", "PLANNING", "ACCELLERATE", "KO"];
exports.ATHLETE_STATUS_DEFAULT = "ONBOARDING";

exports.PERFORMANCE_EXPERT_ROLES = ["HEAD_OF_PERFORMANCE"];