export const USER_TYPE = ["ATHLETE", "PERFORMANCE_EXPERT"];
export const USER_ATHLETE = USER_TYPE[0];
export const USER_PERFORMANCE_EXPERT = USER_TYPE[1];

export const ATHLETE_STATUS = ["ONBOARDING", "PLANNING", "ACCELLERATE", "KO"];
export const ATHLETE_STATUS_DEFAULT = ATHLETE_STATUS[0];

export const PERFORMANCE_EXPERT_ROLES = ["HEAD_OF_PERFORMANCE"];